# Generated by Django 4.2 on 2023-04-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("current", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airqualitydata",
            name="weather_data",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="current.weatherdata",
            ),
        ),
    ]
