# Generated by Django 4.2 on 2023-04-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("temp_c", models.FloatField()),
                ("temp_f", models.FloatField()),
                ("humidity", models.IntegerField()),
            ],
        ),
    ]
