# Generated by Django 4.2 on 2023-04-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("remote", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WeatherData",
        ),
    ]
